-- AlterTable
ALTER TABLE "PlaceRating" ADD COLUMN     "aiAnkommen" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiBuchung" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiGassiUmfeld" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiHaltung" "TSHaltung" NOT NULL DEFAULT 'DNA',
ADD COLUMN     "aiHundAmPlatz" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiNachklang" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiNote" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "aiRuhe" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiSanitaerPrivat" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiStellplatz" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiTotalPoints" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "aiUmgebung" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "aiWiederkommen" "TSValue" NOT NULL DEFAULT 'OKAY',
ADD COLUMN     "haltungVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "userAnkommen" "TSValue",
ADD COLUMN     "userBuchung" "TSValue",
ADD COLUMN     "userGassiUmfeld" "TSValue",
ADD COLUMN     "userHaltung" "TSHaltung",
ADD COLUMN     "userHundAmPlatz" "TSValue",
ADD COLUMN     "userNachklang" "TSValue",
ADD COLUMN     "userNote" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "userRuhe" "TSValue",
ADD COLUMN     "userSanitaerPrivat" "TSValue",
ADD COLUMN     "userStellplatz" "TSValue",
ADD COLUMN     "userTotalPoints" INTEGER,
ADD COLUMN     "userUmgebung" "TSValue",
ADD COLUMN     "userWiederkommen" "TSValue";
